Add tests for cluster subcommand
storageos/vol-test pull request #1
Opened 2017-08-15 11:29 UTC by croomes

Adds basic BATS tests for cluster subcommand.  Doesn't assume anything about the running cluster, other than there is one (accessible via STORAGEOS_HOST)

2017-08-15 15:44 UTC, JoeReid commented
May be my misunderstanding, but don't the BATS tests here require `run $prefix` to ensure they actually get run on the remote hosts? Or is this the desired behaviour for some reason?

2017-08-15 15:50 UTC, rusenask approved these changes
looks great

2017-08-15 15:56 UTC, croomes commented
@JoeReid yes, quite possibly.  I was running them on my laptop going to a remote cluster (also on my laptop), just using the STORAGEOS_HOST var.  I don't think these tests needed to be run on the cluster itself so I left that out.  What I'm unsure about is whether the CLI binary will be up-to-date on the local machine and whether I can reply on the binary in the PATH.

2017-08-15 16:01 UTC, savage-engineer approved these changes
LGTM

2017-08-15 16:04 UTC, JoeReid commented
@croomes Not if we want to also be able to run the BATS locally. I'm not sure about the Jenkins environment but my assumption is that it won't work there either as there will be no special behaviour around using the binaries built from the new CLI_BRANCH env_var and the old VERSION env_var.

2017-08-15 16:35 UTC, JoeReid requested changes
As per my last comment. This would not function as expected on my machine, using the current BATS guide on the wiki. I am also reasonably sure that this would not function correctly in the Jenkins environment either.

@andrelucas would be the one to ask about that though.

The BATS tests now build a custom version of the go-cli as specified by the CLI_VERSION environment variable to allow for a better workflow with multiple repos and it would be a shame to loose that.

Other than this issue it all looks good  :)

2017-08-22 16:38 UTC, JoeReid commented
I have POC'ed this branch on the `release/0.8` pipeline to prove that it shouldn't break the pipelines, and the release candidate passes these tests.

2017-08-22 16:45 UTC, andrelucas commented
Ok. If you haven't seen it yet, it's possible to specify the specific branch for any pipeline, you just have to edit the config_build.groovy to do it - it's not surfaced in the pipeline-add-product-build-branch job yet.

If you're satisfied it won't break feature_etcd=true branches, I'm good with it.

2017-08-22 16:46 UTC, andrelucas approved these changes
Joe has done the due diligence on a representative branch, so that's a 'go'.

2017-08-23 10:36 UTC, JoeReid approved these changes

2017-08-23 10:38 UTC, merged